version: '3.8'

services:
  code:
    image: mcr.microsoft.com/devcontainers/javascript-node:0-18-bullseye@sha256:ed57dd8755b4e75a0426bd10ab1d3a60a22bb21fc2e093801375990978c42fb5
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
  db:
    image: mongo:4@sha256:17330999a8d1e2f8d1805596c48a7dab5265d8da36ac4de20a5c35c32ea2d6b8
    restart: unless-stopped
    volumes:
      - ../database:/data/db
