version: '3.8'

services:
  code:
    image: mcr.microsoft.com/devcontainers/javascript-node:0-18-bullseye@sha256:3511cb8ff39e3b5c45a159e2e56628395b177be04ba9340dbc91919419cb11e8
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
  db:
    image: mongo:4@sha256:967fecde146a0d1ac5ec5805a2c759066b6b94d6fb3977e22292c1d58df244e3
    restart: unless-stopped
    volumes:
      - ../database:/data/db
