version: '3.8'

services:
  code:
    image: mcr.microsoft.com/devcontainers/javascript-node:0-18-bullseye@sha256:c86090d375acf573b098ab0caad8827cb5dd2f2f30ea0d676e38461ea30d75aa
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
  db:
    image: mongo:4@sha256:164c3f8dd6c81f95346c478e7cc447a58804cb661c623d542f416221cd6c037c
    restart: unless-stopped
    volumes:
      - ../database:/data/db
