version: '3.8'

services:
  code:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-18-bullseye@sha256:2fa6162373df30d8a9941e5de522f6283c580f4fa2c467463114f00c91fae743
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
  db:
    image: mongo:4@sha256:52c42cbab240b3c5b1748582cc13ef46d521ddacae002bbbda645cebed270ec0
    restart: unless-stopped
    volumes:
      - ../database:/data/db
