version: '3.8'

services:
  code:
    image: mcr.microsoft.com/devcontainers/javascript-node:0-18-bullseye@sha256:c86090d375acf573b098ab0caad8827cb5dd2f2f30ea0d676e38461ea30d75aa
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
  db:
    image: mongo:4@sha256:d23ec07162ca06646a6329c452643f37494af644d045c002a7b41873981c160d
    restart: unless-stopped
    volumes:
      - ../database:/data/db
