version: '3.8'

services:
  code:
    image: mcr.microsoft.com/devcontainers/javascript-node:0-18-bullseye@sha256:ed57dd8755b4e75a0426bd10ab1d3a60a22bb21fc2e093801375990978c42fb5
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
  db:
    image: mongo:4@sha256:63cbf1ab5888614a9b1c1ff5fe8b2a7a7f2e9a8ca1d6dc4f87c69ae3e06c90f4
    restart: unless-stopped
    volumes:
      - ../database:/data/db
