version: '3.8'

services:
  code:
    image: mcr.microsoft.com/devcontainers/javascript-node:0-18-bullseye@sha256:66f403bf3e8160a10f5ab293a810f1503e17f291fb0166fbe1471cf90c5ee1db
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
  db:
    image: mongo:4@sha256:3ed0b7c5a7724c291db27d8407861bc5db96fafe902a6e9dd4e7657a37a4a4ed
    restart: unless-stopped
    volumes:
      - ../database:/data/db
