version: '3.8'

services:
  code:
    image: mcr.microsoft.com/devcontainers/javascript-node:0-18-bullseye@sha256:8d96097757566369dbb5430c67acb843402f5785ed458136208366a5d3d63c80
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
  db:
    image: mongo:4@sha256:fce002468a7dce312df6cfa0df54f62c24c28ea5e8e47bb343488d67d066f168
    restart: unless-stopped
    volumes:
      - ../database:/data/db
