version: '3.8'

services:
  code:
    image: mcr.microsoft.com/devcontainers/javascript-node:0-18-bullseye@sha256:66f403bf3e8160a10f5ab293a810f1503e17f291fb0166fbe1471cf90c5ee1db
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
  db:
    image: mongo:4@sha256:be5e699466278a9d19884bfe1d6a93bd056ac2cff694b51b87c692f3b1716b5e
    restart: unless-stopped
    volumes:
      - ../database:/data/db
