name: Analysis and Scans
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
    - cron: '0 12 * * 3'

jobs:
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - name: Initialize
      uses: github/codeql-action/init@701f152f28d4350ad289a5e31435e9ab6169a7ca # v2

    - name: Autobuild
      uses: github/codeql-action/autobuild@701f152f28d4350ad289a5e31435e9ab6169a7ca # v2

    - name: Perform analysis and upload results
      uses: github/codeql-action/analyze@701f152f28d4350ad289a5e31435e9ab6169a7ca # v2

  njsscan:
    name: NJS Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - name: Perform scan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '. --sarif --output results.sarif || true'

    - name: Upload results
      uses: github/codeql-action/upload-sarif@701f152f28d4350ad289a5e31435e9ab6169a7ca # v2
      with:
        sarif_file: results.sarif

  ossar:
    name: OSSAR Analysis
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - name: Perform analysis
      uses: github/ossar-action@v1
      id: analysis

    - name: Upload results
      uses: github/codeql-action/upload-sarif@701f152f28d4350ad289a5e31435e9ab6169a7ca # v2
      with:
        sarif_file: ${{ steps.analysis.outputs.sarifFile }}
