name: Docker Compose

on:
  push:
  pull_request:

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3

    - name: Touch .env file
      run: touch ".env"

    - name: Test docker compose build
      run: docker compose build
