name: Testing

on:
  push:
  pull_request:

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - name: Set up node
      uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
      with:
        node-version: "18.x"

    - name: Restore cached modules
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
      id: cache-packages
      with:
        path: node_modules
        key: npm-${{ hashFiles('**/package-lock.json') }}

    - name: Fallback if module cache fails
      run: npm ci
      if: steps.cache-packages.outputs.cache-hit != 'true'

    - name: Run Jest
      run: npm test
